# Default configuration for 311 Data prefect task
# These settings can be overridden with environment variables that follow the pattern:
#     PREFECT__[setting name]
# determines whether Dask should be used to parallelize the flow run
dask = true
# (!) WARNING: setting this to "true" will wipe out whatever is in the target table (e.g. 'requests')
reset_db = false  
# will write to ./output if left blank but can be overridden
temp_folder = ""
# set to local API instance or override with PREFECT__API_URL
api_url = "http://localhost:5000"
# set to local Report Server instance or override with PREFECT__REPORT_SERVER_URL
report_server_url = "https://dash-reporting.tofn9kh9mlm7g.us-east-1.cs.amazonlightsail.com"
# whether the data update is being run in a testing, development or production environment
stage = "Testing"
# whether to vacuum database and reset stats after load
vacuum_db = false

[socrata]
host = "data.lacity.org"
token = "6b5lwk1jHSQTgx7PAVFKOOdt2"

[socrata.datasets]
# dictionary of available socrata datasets
2022 = "i5ke-k6by"
2023 = "4a4x-mna2"

[data]
# years to load
years = [
    2022,
    2023
    ]
# name of table to load
target = "requests"
# identity column
key = "srnumber"
# column to check for last record loaded
recent_column = "updateddate"
# views to refresh when load is complete
views = [
    "service_requests"
    ]

[data.fields]
# fields to pull from socrata and load to database
srnumber = ""
requesttype = ""
status = ""
actiontaken = ""
createddate = ""
updateddate = ""
servicedate = ""
closeddate = ""
requestsource = ""
anonymous = ""
mobileos = ""
owner = ""
nc = "integer"
ncname = ""
policeprecinct = ""
apc = ""
assignto = ""
cd = "integer"
cdmember = ""
address = ""
zipcode = ""
latitude = ""
longitude = ""
