matrix:
  include:
    # - language: python
    #   python:
    #     - "3.6"
    #   before_install:
    #     - cd Project/python
    #   install:
    #     - pip install -r requirements.txt
    #   # command to run tests
    #   script:
    #     - pytest

    - language: node_js
      node_js:
        - "stable"
      cache:
        directories:
        - node_modules
      install:
        - npm install
      script:
        - npm test
        - npm run build
