version: '3.8'

services:
  db:
    container_name: 311-postgres
    image: postgres
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - target: 5432
        published: ${DB_HOST_PORT}
    volumes:
      - backend_data:/var/lib/postgresql/data

  # redis:
  #   container_name: 311-redis
  #   build: ./redis
  #   restart: always
  #   expose:
  #     - 6379

  api:
    container_name: 311-api
    build: ./api
    restart: ${API_RESTART_POLICY}
    env_file: .env
    ports:
      - target: ${APP_PORT}
        published: ${API_HOST_PORT}
    volumes:
      - ./api/:/home/api
    depends_on:
      - db
      # - redis

volumes:
  backend_data:
