files: 'server/'
fail_fast: false
default_language_version:
    python: python3.7
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
    -   id: isort
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v1.5.6'  # Use the sha / tag you want to point at
    hooks:
    -   id: autopep8
-   repo: https://github.com/pycqa/flake8
    rev: '3.9.0'  # pick a git hash / tag to point to
    hooks:
    -   id: flake8
        args: [--max-line-length=88]
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v7.24.0'  # Use the sha / tag you want to point at
    hooks:
    -   id: eslint
        additional_dependencies:
        -   eslint@6.7.2
        -   eslint-config-airbnb@18.0.1
        -   eslint-loader@1.6.1
        -   eslint-plugin-import@2.20.2
        -   eslint-plugin-jsx-a11y@6.2.3
        -   eslint-plugin-react@7.22.0
        -   eslint-plugin-react-hooks@1.7.0
        -   babel-eslint@10.1.0
# -   repo: https://github.com/pre-commit/mirrors-prettier
#     rev: "v2.2.1" # Use the sha or tag you want to point at
#     hooks:
#     -   id: prettier
