repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.4.0
    hooks:
    -   id: reorder-python-imports    
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v1.5.6'  # Use the sha / tag you want to point at
    hooks:
    -   id: autopep8
-   repo: https://github.com/pycqa/flake8
    rev: 'v3.9.0'  # pick a git hash / tag to point to
    hooks:
    -   id: flake8
