# Default configuration for 311 Data prefect task

# These settings can be overridden with environment variables that follow the pattern:
#     PREFECT__[setting name]

# determines whether Dask should be used to parallelize the flow run
dask = true

# (!) WARNING: setting this to "true" will wipe out whatever is in the target table (e.g. 'requests')
reset_db = false  

# will write to ./output if left blank but can be overridden
temp_folder = ""

# set to local API instance or override with PREFECT__API_URL
api_url = "http://localhost:5000"

[socrata]
host = "data.lacity.org"
token = "6b5lwk1jHSQTgx7PAVFKOOdt2"

[socrata.datasets]
# dictionary of available socrata datasets
2020 = "rq3b-xjk8"
2019 = "pvft-t768"
2018 = "h65r-yf5i"
2017 = "d4vt-q4t5"
2016 = "ndkd-k878"
2015 = "ms7h-a45h"

[data]
# years to load
years = [
    2020,
    2019,
    2018,
    2017,
    2016,
    2015
    ]
# name of table to load
target = "requests"
# identity column
key = "srnumber"
# column to check for last record loaded
recent_column = "updateddate"
# views to refresh when load is complete
views = [
    "service_requests"
    ]

[data.fields]
# fields to pull from socrata and load to database
srnumber = ""
requesttype = ""
status = ""
actiontaken = ""
createddate = ""
updateddate = ""
servicedate = ""
closeddate = ""
requestsource = ""
anonymous = ""
mobileos = ""
owner = ""
nc = "integer"
ncname = ""
policeprecinct = ""
apc = ""
assignto = ""
cd = "integer"
cdmember = ""
address = ""
zipcode = ""
latitude = ""
longitude = ""
