name: MasterDeployCI
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 11.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Build project
      run: npm run-script build
    - name: Run Tests
      run: export CI=true && npm run test -- --coverage
      env:
        MAPBOX_TOKEN: ${{ secrets.MAPBOX_TOKEN }}
    -name: Deploy to GH pages
     uses: hackforla/311-data@master
     env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist
        BUILD_SCRIPT: npm install && npm run-script build
