name: MasterDeployCI
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [11.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Build project
      run: npm run-script build
    - name: Run Tests
      run: export CI=true && npm run test -- --coverage
      env:
        MAPBOX_TOKEN: ${{ secrets.MAPBOX_TOKEN }}
    - name: Deploy to GH pages
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: master # The branch the action should deploy from.
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: build # The folder the action should deploy.
        BUILD_SCRIPT: npm rebuild node-sass && npm install && npm run-script build -- --MAPBOX_TOKEN=${{ secrets.MAPBOX_TOKEN }} # The build script the action should run prior to deploying.
