name: Create Release
on:
  push:
    # Sequence of patterns matched against refs/tags
    branches:
      - 'release/v*' # Push events to matching v*, i.e. v1.0, v20.15.10    
jobs:
  build:
    name: Create Release and Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Branch name
        uses: nelonoel/branch-name@v1
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ env.BRANCH_NAME }}
          release_name: Release ${{ env.BRANCH_NAME }}
          body_path: server/docs/release_notes.md
          draft: false
          prerelease: false
      - name: Build and Push API to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          path: server/api
          registry: docker.pkg.github.com
          repository: hackforla/311-data/api
          tags: latest, ${{ env.BRANCH_NAME }}
      - name: Build and Push Prefect to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          path: server/prefect
          registry: docker.pkg.github.com
          repository: hackforla/311-data/prefect
          tags: latest, ${{ env.BRANCH_NAME }}
