name: Create API Image DEV
on:
  push:
    branches:
      - dev
      - master
    paths:
      - 'server/api/**'
jobs:
  build:
    name: Create Dev Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and Push Dev API to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          path: server/api
          repository: la311data/311_data_api
          tags: latest
          tag_with_ref: true
          tag_with_sha: true
