name: Create Images DEV
on:
  push:
    branches:
      - feat-dev-ops-ecs
jobs:
  build:
    name: Create Dev Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and Push Dev API to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          path: server/api
          repository: la311data/311_data_api
          tags: 'latest', 'dev'
          tag_with_ref: true
          tag_with_sha: true
      - name: Build and Push Dev Prefect to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          path: server/prefect
          repository: la311data/311_data_prefect
          tags: 'latest', 'dev'
          tag_with_ref: true
          tag_with_sha: true
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy Amazon ECS update definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: server/update-definition.json
          # service: dev-ecs-service
          # cluster: dev-cluster
      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: server/task-definition.json
          # service: dev-ecs-service
          # cluster: 311-data-cluster
          # wait-for-service-stability: true
