name: Create API Docker Image
on:
  push:
    branches:
      - dev
      - master
    paths:
      - 'server/api/**'
jobs:
  build:
    name: Create Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup environment
        run: |
          echo GITHUB_SHA=${{ github.sha }} >> server/api/.env        
      - name: Build and Push Image to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          path: server/api
          repository: la311data/311_data_api
          tag_with_ref: true
          tag_with_sha: true
