name: Create Prefect Image DEV
on:
  push:
    branches:
      - dev
      - master
    paths:
      - 'server/prefect/**'
jobs:
  build:
    name: Create Dev Prefect Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and Push Dev Prefect to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          path: server/prefect
          repository: la311data/311_data_prefect
          tags: latest
          tag_with_ref: true
          tag_with_sha: true
