name: deploy_backend_dev
on:
  push:
    branches:
      - dev
    paths:
      - 'server/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: server/task-definition.json
        service: api-service
        cluster: dev-cluster
        wait-for-service-stability: true
