name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress run
        uses: cypress-io/github-action@v2.2.2
        with:
          build: npm run build
          start: npm start
          spec: cypress/integration/map_filter.spec.js
          wait-on: http://localhost:3000
